### ISSUE TITLE
pydeck example on the python Shiny website

### ISSUE THREAD

**Issue by ozyhuboi** [posit-dev/py-shinywidgets#146] opened 2024-05-11 04:31 UTC
* shinywidgets version:
* Python version: 
* Operating System:

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

On the pyshiny website https://shiny.posit.co/py/docs/jupyter-widgets.html, there appears to be an error with the PyDeck display. Are there issues displaying pydeck widgets? 
![image](https://github.com/posit-dev/py-shinywidgets/assets/7039525/9bf4f453-940e-4910-9d55-56c8b4f76edd)

**Comment by cpsievert** [comment] 2024-07-24 19:46
Duplicate of https://github.com/posit-dev/py-shiny/issues/1372

Will be fixed by https://github.com/posit-dev/shinylive/pull/161

**Closed by cpsievert** 2024-07-24 19:46 UTC
